spring.application.name=StorageContainer


spring.datasource.url=jdbc:postgresql://localhost:5432/StorageContainer
spring.datasource.username=postgres
spring.datasource.password=#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080


spring.security.oauth2.client.registration.google.client-id=908928381699-48bpaphpmhkgk37k2itsa7vb9329ji9d.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=#

spring.security.oauth2.client.registration.google.scope=openid,profile,email

supabase.bucket=StorageContainer-Bucket
supabase.url=https://iwlfruzbsensjtgjyvmk.supabase.co
supabase.service-key=#

file.upload-dir=uploads