spring.application.name=StorageContainer


spring.datasource.url=jdbc:postgresql://localhost:5432/StorageContainer
spring.datasource.username=postgres
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080


spring.security.oauth2.client.registration.google.client-id=${OAUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email

supabase.bucket=StorageContainer-Bucket
supabase.url=https://iwlfruzbsensjtgjyvmk.supabase.co
supabase.service-key=${SUPABASE_SECRET_KEY}

file.upload-dir=uploads